adverbs = adverbs.concat([
    'lowkey',
    'highkey',
    'unhinged-ly',
    'delulu-ly',
    'bussin-ly',
    'no-cap-ly',
    'sus-ly',
    'rizzfully',
    'mid-ly',
    'slay-ly',
    'fr fr',
    'aggressively',
    'chronically online-ly',
    'giving-ly',
    'ate-and-left-no-crumbs-ly',
    'on god',
    'deadass',
    'sigma-ly',
]);
