nouns = nouns.concat([
    'rizzler',
    'skibidi toilet',
    'sigma',
    'NPC',
    'main character',
    'Stanley cup',
    'Ohio final boss',
    'girl dinner',
    'mewing streak',
    'aura points',
    'delulu bestie',
    'gyatt',
    'fanum tax',
    'baby gronk',
    'side quest',
    'brainrot',
    'ick',
    'situationship',
]);
