adjectives = adjectives.concat([
    'bussin',
    'mid',
    'sus',
    'rizzless',
    'delulu',
    'skibidi',
    'goated',
    'bougie',
    'unhinged',
    'cheugy',
    'sigma',
    'mogged',
    'chronically online',
    'Ohio-level',
    'aura-farming',
    'brainrotted',
    'lowkey iconic',
    'giving main character',
]);
